a

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,6 +1,27 @@
 #!/bin/sh
 #
 
+evalute_module_csv() {
+	INPUT=$1
+
+	[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 1; }
+
+	i=1
+	while IFS=, read group package class instruction_missed instruction_covered branch_missed branch_covered line_missed line_covered complexity_missed complexity_covered method_missed method_covered
+	do
+		test $i -eq 1 && ((i=i+1)) && continue
+
+		if [[ $line_covered -eq 0 ]]
+		then
+		    echo "There is no test run for $class in $package"
+		else
+			line_total=$(($line_covered + $line_missed))
+		    echo "$line_covered out of $line_total lines are tested at $class in $package"
+		fi
+	done < $INPUT
+}
+
+
 if ./gradlew debugSLKCoverage  ;then
 	echo ""
 else
@@ -10,22 +31,8 @@ else
 fi
 
 
-INPUT=./build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
+evalute_module_csv ./app/build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
+evalute_module_csv ./second/build/covReportDir/debugSLKCoverage/debugSLKCoverage.csv
 
-[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 1; }
-
-i=1
-while IFS=, read group package class instruction_missed instruction_covered branch_missed branch_covered line_missed line_covered complexity_missed complexity_covered method_missed method_covered
-do
-	test $i -eq 1 && ((i=i+1)) && continue
-
-	if [[ $line_covered -eq 0 ]]
-	then
-	    echo "There is no test run for $class in $package"
-	else
-		line_total=$(($line_covered + $line_missed))
-	    echo "$line_covered out of $line_total lines are tested at $class in $package"
-	fi
-done < $INPUT
 echo ""
 echo ""
